Sprint 3
AMorozov-web/middle.messenger.praktikum.yandex pull request #3
Opened 2022-06-23 08:59 UTC by AMorozov-web

2022-06-23 12:26 UTC, podlovchenko requested changes
Привет)
Не выполнена часть задания
<img width="613" alt="Снимок экрана 2022-06-23 в 15 22 30" src="https://user-images.githubusercontent.com/22602747/175297990-e8e997b9-0d24-4ab2-b6dc-8277602f16ee.png">
При обновлении страницы http://localhost:3000/profile Cannot GET /profile

С датами проблема
<img width="653" alt="Снимок экрана 2022-06-23 в 15 23 51" src="https://user-images.githubusercontent.com/22602747/175297881-374696df-882d-4329-8203-5d6c1a325e0f.png">
0 мая?
Последнее сообщение почему-то 4 мая и вверху чата

2022-06-23 12:26 UTC, podlovchenko commented on src/api/auth.ts
> +        },
Можно внести внутрь httpTransport

2022-06-23 12:26 UTC, podlovchenko commented on src/api/auth.ts
> +      .then((response) => JSON.parse(response));
И это, чтобы не дублировать код

2022-06-23 14:36 UTC, AMorozov-web commented
> Внес изменения, но не смог толком проверить кейс с нулевым днем, поскольку у меня нет учетки чата, где много сообщений в разные дни

2022-06-23 14:40 UTC, AMorozov-web commented on src/api/auth.ts
> +        },
В данном случае я не стал это делать, поскольку API, предоставленное для обучения ведет себя не совсем корректно в плане заголовков, в частности если например ты отправляешь FormData, то тебе вообще не надо указывать заголовков. Эту логику я и поместил внутрь HttpTransport, а заголовки для надежности посчитал нужным указывать вручную, поскольку это делает настройку каждого эндпоинта гибкой, а лишняя логика внутри HttpTransport могла породить n-ое количество багов

2022-06-23 14:42 UTC, AMorozov-web commented on src/api/auth.ts
> +      .then((response) => JSON.parse(response));
От сервера не всегда приходит ответ, плюс не все ответы от сервера мне нужно было парсить, поэтому я сделал парсинг внутри API и только там, где нужно

2022-06-24 12:18 UTC, podlovchenko commented
Проблема с датами осталась, отправляю сообщения и отображается 5 мая, хотя в ответе запроса чатов приходит правильная дата

2022-06-24 15:09 UTC, AMorozov-web commented
> Проблема с датами осталась, отправляю сообщения и отображается 5 мая, хотя в ответе запроса чатов приходит правильная дата

2022-06-24 15:10 UTC, AMorozov-web commented
> Проблема с датами осталась, отправляю сообщения и отображается 5 мая, хотя в ответе запроса чатов приходит правильная дата

Это называется "нельзя писать код ночью"  *facepalm*

2022-06-24 17:16 UTC, podlovchenko commented
5 июня, а сегодня 24) 
<img width="1173" alt="Снимок экрана 2022-06-24 в 20 15 08" src="https://user-images.githubusercontent.com/22602747/175610327-838490d9-7c7c-44cf-9d0e-c10de00eb848.png">
Впереди целые выходные, не спеши)

2022-06-24 17:23 UTC, podlovchenko commented on src/utils/utils.ts
> +  const day = date.getDay();
Метод не тот

2022-06-24 17:34 UTC, AMorozov-web commented on src/utils/utils.ts
> +  const day = date.getDay();
Исправил, сорри за спешку, только полчаса назад увидел в чате, что помимо выходных есть еще 3 дня)

2022-06-25 14:32 UTC, podlovchenko commented
Работа принята)

2022-06-25 15:12 UTC, merged